### ISSUE TITLE
backend .env

### ISSUE THREAD

**Issue by DidibabaQiu** [m8schmit/ecovacs-stack#1]
Dear sir, 

could you please teach me how to get my deebot BOTID, BOTCLASS, and RESOURCE? i open my ECOVACS APP but cannot find them.

**Comment by m8schmit** [comment]
Hi, sorry it's not well documented. Fortunately it's pretty simple to achieve:
- Follow any other steps of the tutorial (https://github.com/m8schmit/ecovacs-stack#how-to-install), the `dns-mask` config, your local ip in the `.env` in the frontend and backend folders, etc.
- Then start the app with `docker-compose up`.
- Once everything seems good and ready, start your bot.
- It should connected to the local server and you should see a log looking like:
```
 Client Connected: YOUR-BOT-ID@YOUR-BOT-CLASS/YOUR-BOT-RESOURCE, to broker SOME-RANDOM-UUID
 ```
 now you can get these three values, copy them in the `.env` and restart the app (`docker-compose restart`), no need to restart the bot.

**Comment by DidibabaQiu** [comment]
> Hi, sorry it's not well documented. Fortunately it's pretty simple to achieve:
> 
> * Follow any other steps of the tutorial (https://github.com/m8schmit/ecovacs-stack#how-to-install), the `dns-mask` config, your local ip in the `.env` in the frontend and backend folders, etc.
> * Then start the app with `docker-compose up`.
> * Once everything seems good and ready, start your bot.
> * It should connected to the local server and you should see a log looking like:
> 
> ```
>  Client Connected: YOUR-BOT-ID@YOUR-BOT-CLASS/YOUR-BOT-RESOURCE, to broker SOME-RANDOM-UUID
> ```
> 
> now you can get these three values, copy them in the `.env` and restart the app (`docker-compose restart`), no need to restart the bot.

Thank you very much for your guidance, I will try again

**Comment by m8schmit** [comment]
@DidibabaQiu did you manage to get your bot infos and use the app?

**Comment by FX1-7** [comment]
Hi,

I'm having the same issue getting my bot_id, class and resource variables. The bot does not seem to auto connect, I have been turning the bot off fully and turning it on again. When I start a clean it still does not connect to the local server.

I've attached a screenshot of what our running environment looks like:

![Screenshot](https://github.com/m8schmit/ecovacs-stack/assets/31273773/7eb2bc90-7126-4f76-b54b-78d37d6eb682)

**Comment by nhutngohuu-kozocom** [comment]
Hi @m8schmit 

>  Client Connected: YOUR-BOT-ID@YOUR-BOT-CLASS/YOUR-BOT-RESOURCE, to broker SOME-RANDOM-UUID

I can't find that. Show in my local, ip show like image. Could you help me get my deebot BOTID, BOTCLASS, and RESOURCE?

![image](https://github.com/user-attachments/assets/164f0cd7-ad69-4070-84bd-87a9ed843307)

**Comment by ngohuunhut** [comment]
Hi @m8schmit 

>  Client Connected: YOUR-BOT-ID@YOUR-BOT-CLASS/YOUR-BOT-RESOURCE, to broker SOME-RANDOM-UUID

I cant find that. Could you help me get id, class and resource? I have built your docker but the message like this
![image](https://github.com/user-attachments/assets/9472a5fd-badb-4597-8f43-7a3c69ffa06d)
